runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/index.html
  upload: website/index\.html
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: website/\1
  upload: website/(.*\.html)
  secure: always

- url: /css
  static_dir: website/css
  secure: always

- url: /js
  static_dir: website/js
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /favicon\.ico
  static_files: website/img/favicon.ico
  upload: website/favicon\.ico
  secure: always

- url: /(.*\.(gif|png|jpg))$
  static_files: website/\1
  upload: website/.*\.(gif|png|jpg)$

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.libsvm$
- ^(.*/)?\.jar$
- .*\bIcon\b.*